# Build a Text Cleaner

In [2]:
import pandas as pd

In [3]:
data = [
    "This is a simple sentence!",
    "I am learning NLP, and it is fun.",
    "The movie was very good and interesting.",
    "This is not bad at all.",
    "He is going to the market."
]

df = pd.DataFrame(data, columns=["Sentence"])
df

                                   Sentence
0                This is a simple sentence!
1         I am learning NLP, and it is fun.
2  The movie was very good and interesting.
3                   This is not bad at all.
4                He is going to the market.

In [4]:
def to_lower(text):
    return text.lower()

In [5]:
def remove_punctuation(text):
    punctuations = "!?,.:-;()[]{}'\""
    for p in punctuations:
        text = text.replace(p, "")
    return text

In [6]:
stopwords = [
    "is", "am", "are", "the", "and", "to", "a", "of", "in", "it", "was"
]

In [7]:
def remove_stopwords(text):
    words = text.split()
    filtered_words = []
    
    for word in words:
        if word not in stopwords:
            filtered_words.append(word)
    
    return " ".join(filtered_words)

In [8]:
df["Cleaned"] = df["Sentence"].apply(to_lower)
df["Cleaned"] = df["Cleaned"].apply(remove_punctuation)
df["Cleaned"] = df["Cleaned"].apply(remove_stopwords)
df

                                   Sentence                      Cleaned
0                This is a simple sentence!         this simple sentence
1         I am learning NLP, and it is fun.           i learning nlp fun
2  The movie was very good and interesting.  movie very good interesting
3                   This is not bad at all.          this not bad at all
4                He is going to the market.              he going market

In [9]:
for i in range(len(df)):
    print("Original :", df["Sentence"][i])
    print("Cleaned  :", df["Cleaned"][i])
    print("-"*40)

Original : This is a simple sentence!
Cleaned  : this simple sentence
----------------------------------------
Original : I am learning NLP, and it is fun.
Cleaned  : i learning nlp fun
----------------------------------------
Original : The movie was very good and interesting.
Cleaned  : movie very good interesting
----------------------------------------
Original : This is not bad at all.
Cleaned  : this not bad at all
----------------------------------------
Original : He is going to the market.
Cleaned  : he going market
----------------------------------------